// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:eda13ac3-9231-49f3-a82e-7b846d39b880",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_w6zQdLpj4",
    "aws_user_pools_web_client_id": "66tjjb2puvtnqvvut8lek9v56n"
};


export default awsmobile;
